service: dynamodb-experience

provider:
  name: aws
  runtime: nodejs8.10

functions:
  list:
    handler: handlers/list.list
    events:
      - http:
          path: dynamo/list
          method: get
          cors: true
  listDate:
    handler: handlers/list.listDate
    events:
      - http:
          path: dynamo/list/Date/{from}/{to?}
          method: get
          cors: true
  create:
    handler: handlers/create.create
    events:
      - http:
          path: dynamo/create
          method: post
          cors: true


plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  tableName: 'dynamo-experience'
  dynamodb:
    start:
      port: 3004
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: dynamo-experience
            sources: [./seed/dynamo-experience-data.json]
  serverless-offline:
    port: 3000

iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:*:*:table/dynamo-experience"

resources:
  Resources:
    dynamoExperience:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: dynamo-experience
        KeySchema:  
          - AttributeName: ID
            KeyType: HASH
          - AttributeName: Title
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: Title
            AttributeType: S
          - AttributeName: Date
            AttributeType: S
        ProvisionedThroughput:   
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        LocalSecondaryIndexes:
          - IndexName: dynamo-experience-byDate
            KeySchema:
              - AttributeName: ID
                KeyType: HASH
              - AttributeName: Date
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
